import { API } from 'themes/config';
export const DEPENDENCIES = [
  API.USERS,
  API.ACTORS,
  API.ACTIONS,
  API.CATEGORIES,
  API.TAXONOMIES,
  API.INDICATORS,
  API.USER_ACTORS,
  API.USER_ACTIONS,
  API.MEMBERSHIPS,
  API.ACTOR_ACTIONS,
  API.ACTOR_CATEGORIES,
  API.ACTION_INDICATORS,
  API.ACTION_ACTORS,
  API.ACTION_CATEGORIES,
];
