import { API } from 'themes/config';
export const DEPENDENCIES = [
  API.ACTORS,
  API.ACTIONS,
  API.ACTOR_ACTIONS,
  API.ACTION_CATEGORIES,
  API.CATEGORIES,
  API.MEMBERSHIPS,
  API.INDICATORS,
  API.ACTION_INDICATORS,
];
