import { API } from 'themes/config';
// required for selectActorsWithPositionsData
import { ACTORS_WITH_POSITIONS_DEPENDENCIES } from 'containers/App/selectors';

export const DEPENDENCIES = [
  ...new Set([
    ...ACTORS_WITH_POSITIONS_DEPENDENCIES,
    API.ACTORS,
    API.ACTIONS,
    API.ACTOR_ACTIONS,
    API.ACTION_ACTIONS,
    API.ACTION_CATEGORIES,
    // API.ACTORTYPES,
    // API.ACTIONTYPES,
    // API.RESOURCETYPES,
    // API.ACTORTYPE_TAXONOMIES,
    // API.ACTIONTYPE_TAXONOMIES,
    // API.TAXONOMIES,
    API.CATEGORIES,
    API.MEMBERSHIPS,
    // API.USERS,
    // API.USER_ACTIONS,
    // API.USER_ROLES,
    API.INDICATORS,
    API.ACTION_INDICATORS,
  ]),
];
