import { API } from 'themes/config';

// required for selectActorsWithPositionsData
import { ACTORS_WITH_POSITIONS_DEPENDENCIES } from 'containers/App/selectors';

export const DEPENDENCIES = [
  ...new Set([
    ...ACTORS_WITH_POSITIONS_DEPENDENCIES,
    API.USERS,
    API.USER_ROLES,
    API.CATEGORIES,
    API.TAXONOMIES,
    API.ACTIONTYPES,
    API.ACTORTYPES,
    API.ACTIONTYPE_TAXONOMIES,
    API.ACTORS,
    API.ACTIONS,
    API.RESOURCES,
    API.ACTOR_ACTIONS,
    API.ACTION_ACTORS,
    API.ACTION_RESOURCES,
    API.MEMBERSHIPS,
    API.ACTOR_CATEGORIES,
    API.ACTION_CATEGORIES,
    API.INDICATORS,
    API.ACTION_INDICATORS,
    API.USER_ACTORS,
    API.USER_ACTIONS,
  ]),
];
