import { API } from 'themes/config';

export const DEPENDENCIES = [
  API.USERS,
  API.ROLES,
  API.USER_ROLES,
  API.CATEGORIES,
  API.TAXONOMIES,
  API.USER_CATEGORIES,
  API.USER_ACTORS,
  API.USER_ACTIONS,
  API.ACTORS,
  API.ACTIONS,
  API.ACTIONTYPES,
  API.ACTOR_ACTIONS,
  API.ACTION_ACTORS,
  API.ACTION_RESOURCES,
  API.ACTION_INDICATORS,
  API.RESOURCES,
  API.INDICATORS,
  API.ACTOR_CATEGORIES,
  API.ACTION_CATEGORIES,
  API.MEMBERSHIPS,
];
